'use client';
import './ax-input-text.css';

import React, {
  ChangeEvent,
  CSSProperties,
  FocusEvent,
  forwardRef,
  MouseEvent,
  ReactNode,
  useId,
  useState,
} from 'react';
import { Icon, IconName } from '@/assets/icons';
import AXInputLabel, { AXInputLabelProps } from '../ax-input-label/ax-input-label';

// region Interfaces
export type AXInputTextSize = 'sm' | 'md' | 'lg';
export type AXInputTextStatus = 'default' | 'error' | 'success' | 'warning';
export type AXInputTextLayout = 'vertical' | 'horizontal';

export interface AXInputTextProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size' | 'prefix'> {
  // Label Props
  /** Text of the label */
  propsLabel?: string;
  /** Mandatory indicator symbol/text (e.g. "*") */
  propsIsMandatory?: string;
  /** Currency text or symbol (e.g. "($)", "USD") */
  propsCurrency?: string;
  /** Badge counter / text */
  propsBadge?: number | string;
  /** Custom label props override object */
  propsLabelProps?: Partial<AXInputLabelProps>;

  // Layout & Styling
  /** Layout orientation: 'vertical' (default) or 'horizontal' */
  propsLayout?: AXInputTextLayout;
  /** Input size: 'sm', 'md' (default), 'lg' */
  propsSize?: AXInputTextSize;
  /** Validation status state */
  propsStatus?: AXInputTextStatus;
  /** Container className */
  propsContainerClassName?: string;
  /** Container inline styles */
  propsContainerStyle?: CSSProperties;
  /** Input wrapper className */
  propsWrapperClassName?: string;
  /** Native input element className */
  propsClassName?: string;
  /** Native input element inline style */
  propsStyle?: CSSProperties;

  // Icons & Affixes
  /** Icon name or ReactNode to display before the text */
  propsStartIcon?: IconName | string | ReactNode;
  /** Icon name or ReactNode to display after the text */
  propsEndIcon?: IconName | string | ReactNode;
  /** Prefix text / addon */
  propsPrefix?: ReactNode;
  /** Suffix text / addon */
  propsSuffix?: ReactNode;
  /** Shows a clear (x) button when input has value */
  propsAllowClear?: boolean;
  /** Shows eye icon to toggle password visibility (for type="password") */
  propsShowPasswordToggle?: boolean;

  // Messages & Character Count
  /** Helper text below input */
  propsHelperText?: ReactNode;
  /** Error message below input (also sets status to error) */
  propsErrorMessage?: ReactNode;
  /** Shows character count e.g. (10/50) */
  propsShowCount?: boolean;
  /** Maximum length allowed */
  propsMaxLength?: number;

  // Input Control Props
  /** Controlled input value */
  propsValue?: string | number;
  /** Initial uncontrolled default value */
  propsDefaultValue?: string | number;
  /** Placeholder text */
  propsPlaceholder?: string;
  /** HTML input type (default: 'text') */
  propsType?: string;
  /** HTML input id (autogenerated if not provided) */
  propsId?: string;
  /** HTML input name */
  propsName?: string;
  /** Disabled state */
  propsIsDisabled?: boolean;
  /** Readonly state */
  propsIsReadOnly?: boolean;
  /** Required state */
  propsIsRequired?: boolean;
  /** Required state shorthand */
  propsRequired?: boolean;
  /** Autocomplete attribute */
  propsAutoComplete?: string;
  /** Autofocus attribute */
  propsAutoFocus?: boolean;

  // Events
  /** On change event handler */
  propsOnChange?: (event: ChangeEvent<HTMLInputElement>) => void;
  /** On focus event handler */
  propsOnFocus?: (event: FocusEvent<HTMLInputElement>) => void;
  /** On blur event handler */
  propsOnBlur?: (event: FocusEvent<HTMLInputElement>) => void;
  /** On clear click handler */
  propsOnClear?: () => void;
}

// region Main Component
export const AXInputText = forwardRef<HTMLInputElement, AXInputTextProps>((props, ref) => {
  const {
    propsLabel,
    propsIsMandatory,
    propsCurrency,
    propsBadge,
    propsLabelProps,
    propsLayout = 'vertical',
    propsSize = 'md',
    propsStatus = 'default',
    propsContainerClassName,
    propsContainerStyle,
    propsWrapperClassName,
    propsClassName,
    propsStyle,
    propsStartIcon,
    propsEndIcon,
    propsPrefix,
    propsSuffix,
    propsAllowClear = false,
    propsShowPasswordToggle = true,
    propsHelperText,
    propsErrorMessage,
    propsShowCount = false,
    propsMaxLength,
    propsValue,
    propsDefaultValue,
    propsPlaceholder,
    propsType = 'text',
    propsId,
    propsName,
    propsIsDisabled = false,
    propsIsReadOnly = false,
    propsIsRequired,
    propsRequired,
    required,
    propsAutoComplete,
    propsAutoFocus = false,
    propsOnChange,
    propsOnFocus,
    propsOnBlur,
    propsOnClear,
    ...restInputProps
  } = props;

  const generatedId = useId();
  const inputId = propsId || `ax-input-${generatedId}`;
  const isInputRequired = Boolean(propsIsRequired || propsRequired || required);
  
  // State for internal value tracking (for clear & count support in uncontrolled mode)
  const [internalValue, setInternalValue] = useState<string>(
    propsValue !== undefined ? String(propsValue) : propsDefaultValue !== undefined ? String(propsDefaultValue) : ''
  );
  const [isPasswordVisible, setIsPasswordVisible] = useState(false);

  const currentValue = propsValue !== undefined ? String(propsValue) : internalValue;
  const isPasswordType = propsType === 'password';
  const effectiveType = isPasswordType && isPasswordVisible ? 'text' : propsType;
  const effectiveStatus = propsErrorMessage ? 'error' : propsStatus;

  // Handlers
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    if (propsValue === undefined) {
      setInternalValue(e.target.value);
    }
    propsOnChange?.(e);
  };

  const handleClear = (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    e.stopPropagation();
    if (propsValue === undefined) {
      setInternalValue('');
    }
    propsOnClear?.();
    if (propsOnChange) {
      const syntheticEvent = {
        target: { value: '', name: propsName },
        currentTarget: { value: '', name: propsName },
      } as ChangeEvent<HTMLInputElement>;
      propsOnChange(syntheticEvent);
    }
  };

  const togglePasswordVisibility = (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsPasswordVisible((prev) => !prev);
  };

  // Helper renderer for icon
  const renderIcon = (icon: IconName | string | ReactNode, defaultSize: number) => {
    if (!icon) return null;
    if (typeof icon === 'string') {
      return <Icon name={icon as IconName} size={defaultSize} />;
    }
    return icon;
  };

  const iconSize = propsSize === 'sm' ? 14 : propsSize === 'lg' ? 18 : 16;
  const hasValue = Boolean(currentValue && currentValue.length > 0);

  // Wrapper CSS classes
  const wrapperClasses = [
    'ax-input-text-wrapper',
    `ax-input-text-${propsSize}`,
    effectiveStatus !== 'default' ? `ax-input-status-${effectiveStatus}` : '',
    propsIsDisabled ? 'ax-input-text-disabled' : '',
    propsIsReadOnly ? 'ax-input-text-readonly' : '',
    propsWrapperClassName,
  ]
    .filter(Boolean)
    .join(' ');

  // Container CSS classes
  const containerClasses = [
    'ax-input-text-container',
    propsLayout === 'horizontal' ? 'ax-input-horizontal' : 'ax-input-vertical',
    propsContainerClassName,
  ]
    .filter(Boolean)
    .join(' ');

  // region Main Return
  return (
    <div className={containerClasses} style={propsContainerStyle}>
      {/* Label */}
      {(propsLabel || propsLabelProps) && (
        <AXInputLabel
          propsHtmlFor={inputId}
          propsLabel={propsLabel || ''}
          propsIsMandatory={propsIsMandatory || (isInputRequired ? '*' : undefined)}
          propsCurrency={propsCurrency}
          propsBadge={propsBadge}
          propsIsDisabled={propsIsDisabled}
          {...propsLabelProps}
        />
      )}

      {/* Input Box Wrapper */}
      <div className={wrapperClasses}>
        {/* Start Icon */}
        {propsStartIcon && (
          <span className="ax-input-text-start-icon" aria-hidden="true">
            {renderIcon(propsStartIcon, iconSize)}
          </span>
        )}

        {/* Prefix Addon */}
        {propsPrefix && <span className="ax-input-text-prefix">{propsPrefix}</span>}

        {/* HTML Input Control */}
        <input
          ref={ref}
          id={inputId}
          name={propsName}
          type={effectiveType}
          value={propsValue !== undefined ? propsValue : internalValue}
          defaultValue={propsValue !== undefined ? undefined : propsDefaultValue}
          placeholder={propsPlaceholder}
          disabled={propsIsDisabled}
          readOnly={propsIsReadOnly}
          required={isInputRequired}
          maxLength={propsMaxLength}
          autoComplete={propsAutoComplete}
          autoFocus={propsAutoFocus}
          className={`ax-input-text-control ${propsClassName || ''}`.trim()}
          style={propsStyle}
          onChange={handleChange}
          onFocus={propsOnFocus}
          onBlur={propsOnBlur}
          aria-invalid={effectiveStatus === 'error'}
          aria-describedby={
            propsErrorMessage
              ? `${inputId}-error`
              : propsHelperText
              ? `${inputId}-helper`
              : undefined
          }
          {...restInputProps}
        />

        {/* Clear Button */}
        {propsAllowClear && hasValue && !propsIsDisabled && !propsIsReadOnly && (
          <button
            type="button"
            className="ax-input-text-action-btn"
            onClick={handleClear}
            title="Clear input"
            aria-label="Clear input"
            tabIndex={-1}
          >
            <Icon name="x-circle-fill" size={iconSize} />
          </button>
        )}

        {/* Password Visibility Toggle */}
        {isPasswordType && propsShowPasswordToggle && !propsIsDisabled && (
          <button
            type="button"
            className="ax-input-text-action-btn"
            onClick={togglePasswordVisibility}
            title={isPasswordVisible ? 'Hide password' : 'Show password'}
            aria-label={isPasswordVisible ? 'Hide password' : 'Show password'}
            tabIndex={-1}
          >
            <Icon name={isPasswordVisible ? 'eye-slash' : 'eye'} size={iconSize} />
          </button>
        )}

        {/* Suffix Addon */}
        {propsSuffix && <span className="ax-input-text-suffix">{propsSuffix}</span>}

        {/* End Icon */}
        {propsEndIcon && (
          <span className="ax-input-text-end-icon" aria-hidden="true">
            {renderIcon(propsEndIcon, iconSize)}
          </span>
        )}
      </div>

      {/* Footer / Helper / Error Messages / Character Counter */}
      {(propsErrorMessage || propsHelperText || propsShowCount) && (
        <div className="ax-input-text-footer">
          {propsErrorMessage ? (
            <span id={`${inputId}-error`} className="ax-input-text-error-message" role="alert">
              {propsErrorMessage}
            </span>
          ) : propsHelperText ? (
            <span id={`${inputId}-helper`} className="ax-input-text-message">
              {propsHelperText}
            </span>
          ) : (
            <span />
          )}

          {propsShowCount && (
            <span
              className={`ax-input-text-counter ${
                propsMaxLength && currentValue.length > propsMaxLength
                  ? 'ax-input-text-counter-exceeded'
                  : ''
              }`.trim()}
              aria-live="polite"
            >
              {currentValue.length}
              {propsMaxLength ? `/${propsMaxLength}` : ''}
            </span>
          )}
        </div>
      )}
    </div>
  );
});

AXInputText.displayName = 'AXInputText';

export default AXInputText;
