export const SampleNotifications = [
  {
    id: 1,
    type: 'action',
    title: 'Leave approval required',
    description: 'Rahul requested leave for tomorrow.',
    isRead: false,
    createdAt: '2026-10-01T10:30:00',
    readAt: null,
    referenceId: 101,
  },
  {
    id: 2,
    type: 'action',
    title: 'Fee concession review',
    description: 'Fee concession request submitted by Priya.',
    isRead: false,
    createdAt: '2026-09-30T15:15:00',
    readAt: null,
    referenceId: 201,
  },
  {
    id: 3,
    type: 'alert',
    title: 'Your leave has been approved',
    description: 'Your leave request for tomorrow has been approved.',
    isRead: false,
    createdAt: '2026-10-01T09:45:00',
    readAt: null,
    referenceId: 102,
  },
  {
    id: 4,
    type: 'alert',
    title: 'Monthly attendance updated',
    description: 'Your attendance report for September is now available.',
    isRead: true,
    createdAt: '2026-09-30T16:00:00',
    readAt: '2026-09-30T17:10:00',
    referenceId: 301,
  },
  {
    id: 5,
    type: 'general',
    title: 'Sports Day Tomorrow',
    description: 'Sports Day starts tomorrow at 9:00 AM.',
    isRead: false,
    createdAt: '2026-10-01T08:00:00',
    readAt: null,
    referenceId: 401,
  },
  {
    id: 6,
    type: 'general',
    title: 'Annual Day',
    description: 'Annual Day will be held on 10 October.',
    isRead: true,
    createdAt: '2026-09-30T16:30:00',
    readAt: '2026-09-30T18:00:00',
    referenceId: 402,
  },
];

export default SampleNotifications;
